#!/bin/sh

if [ ! -d "$HOME/.dotfiles" ]; then
    printf "\033[00;36mcloning dotfiles\033[0m\n"
    git clone -q https://github.com/wbyoung/dotfiles.git "$HOME/.dotfiles"
fi

"$HOME/.dotfiles/bin/dot" "$@"
