set nocompatible
let mapleader=","
let g:snipMate = { 'snippet_version' : 1 }

if filereadable(expand("$VIM_SETTINGS/plugins.vim"))
  source $VIM_SETTINGS/plugins.vim
endif

for fpath in split(globpath('$VIM_SETTINGS/extras', '*.vim'), '\n')
  exe 'source' fpath
endfor

for fpath in split(globpath('$VIM_SETTINGS/plugin-settings', '*.vim'), '\n')
  exe 'source' fpath
endfor

for fpath in split(globpath('$VIM_SETTINGS/settings', '*.vim'), '\n')
  exe 'source' fpath
endfor
