#!/usr/bin/env bash
# vim: set ft=bash :

cd "$(dirname "$0")/.."
source bin/dot

setup-main() {
  script-init "$@"
  write-settings
  install-packages
}

write-settings() {
  run-cmd write-gnome-settings
  run-cmd write-ptyxis-settings
}

install-packages() {
  if [ "$(dconf read /localhost/wbyoung/dot/packages 2>/dev/null)" = "true" ] && \
    [ "$FEDORA_PACKAGES" != "1" ]; then
    printf "${RED}${BOLD}Packages have already been installed.${RESET} " 1>&2
    printf "${YELLOW}Re-run with FEDORA_PACKAGES=1${RESET}\n" 1>&2
    return 1
  else
    dconf write /localhost/wbyoung/dot/packages "true"
  fi

  # ask for the administrator password upfront
  log-info "Requesting admin password prior to installing apps"
  run-cmd sudo -v

  run-cmd install-gnome-extensions
  run-cmd install-brave
  run-cmd install-devtools
  run-cmd install-vscode
  run-cmd install-docker

  is-config-set "zsh-config" \
    && run-cmd install-zsh-plugin-dependencies
  is-config-set "vim-config" \
    && run-cmd install-vim
  is-config-set "git-config" \
    && run-cmd install-gh
}

write-gnome-settings() {
  # map capslock to escape while retaining 'lv3:ralt_switch' default setting
  gsettings set org.gnome.desktop.input-sources xkb-options "['lv3:rwin_switch', 'caps:escape_shifted_capslock', 'compose:ralt']"
  gsettings set org.gnome.settings-daemon.plugins.housekeeping donation-reminder-enabled false

  # set icon for code folder
  mkdir -p "$HOME/Code"
  gio set -t string "$HOME/Code" metadata::custom-icon file:///usr/share/icons/Adwaita/scalable/places/folder-documents.svg

  # symlink to have screenshots saved to desktop
  if [ -d "$HOME/Pictures/Screenshots" ] && ! [ -L "$HOME/Pictures/Screenshots" ]; then
    rmdir "$HOME/Pictures/Screenshots"
    ln -s "../Desktop" $HOME/Pictures/Screenshots
  fi
}

write-ptyxis-settings() {
  terminal_profile_id=$(dconf read /org/gnome/Ptyxis/default-profile-uuid)
  terminal_profile_id=${terminal_profile_id#\'}
  terminal_profile_id=${terminal_profile_id%\'}

  for name in "corrected" "full-invert"; do
    ln -fs \
      "${HOME}/.dotfiles/fedora/solarized-${name}.palette" \
      "${HOME}/.local/share/org.gnome.Ptyxis/palettes/solarized-${name}.palette"
  done

  dconf write /org/gnome/Ptyxis/Profiles/$terminal_profile_id/bold-is-bright "false"
  dconf write /org/gnome/Ptyxis/Profiles/$terminal_profile_id/palette "'solarized-full-invert'"
  dconf write /org/gnome/Ptyxis/Profiles/$terminal_profile_id/preserve-directory "'safe'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-1 "'<Alt>exclam'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-10 "'<Alt>parenright'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-2 "'<Alt>at'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-3 "'<Alt>numbersign'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-4 "'<Alt>dollar'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-5 "'<Alt>percent'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-6 "'<Alt>asciicircum'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-7 "'<Alt>ampersand'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-8 "'<Alt>asterisk'"
  dconf write /org/gnome/Ptyxis/Shortcuts/focus-tab-9 "'<Alt>parenleft'"
  dconf write /org/gnome/Ptyxis/Shortcuts/reset "''"
  dconf write /org/gnome/Ptyxis/Shortcuts/reset-and-clear "'<Shift><Control>k'"
}

install-gnome-extensions() {
  pip3 install --quiet --user --upgrade gnome-extensions-cli
  gext install \
    appindicatorsupport@rgcjonas.gmail.com \
    background-logo@fedorahosted.org \
    gTile@vibou \
    nightthemeswitcher@romainvigier.fr
}

install-brave() {
  sudo dnf -yq config-manager addrepo 2> /dev/null \
    --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    brave-browser
}

install-devtools() {
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    gettext \
    git \
    patch \
    patchutils \
    gcc-c++ \
    python3-devel \
    python3.13 \
    python3.13-devel
}

install-zsh-plugin-dependencies() {
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    chroma
}

install-vim() {
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    neovim
  pip3 install --quiet --user --upgrade pynvim # required for jedi-vim in neovim
}

install-vscode() {
  sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
  echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" \
    | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
  dnf check-update &> /dev/null
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    code # or code-insiders
}

install-docker() {
  local has_docker_group=no

  if getent group docker > /dev/null; then
    has_docker_group=yes
  fi

  sudo dnf -yq config-manager addrepo 2> /dev/null \
    --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo
  sudo dnf --assumeyes --quiet install 2> /dev/null \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin
  (cat /etc/docker/daemon.json 2> /dev/null || echo '{}') \
    | jq '."log-driver" = "local" | ."log-opts"."max-size" = "10m"' \
    | sudo tee /etc/docker/daemon.json > /dev/null
  sudo systemctl enable --now docker
  sudo usermod -aG docker $USER

  # note: the install instructions suggest to run `newgrp docker` here, but that
  # creates a new subshell, so we just need to warn if the user should take
  # action.
  if [ "$has_docker_group" = "no" ]; then
    log-warning "docker group added; re-login for permissions to take effect"
  fi
}

install-gh() {
  sudo dnf -yq config-manager addrepo 2> /dev/null \
    --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
  sudo dnf --assumeyes --quiet install --repo gh-cli 2> /dev/null \
    gh
}

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
  setup-main "$@"
fi
