set -g default-shell "${SHELL}"
set -g default-command "${SHELL}"
set -a terminal-features 'xterm-256color:RGB'
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "remote-copy"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "remote-copy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "remote-copy"
setenv -g PATH "${HOME}/.dotfiles/bin:${PATH}"
setenv -g TERMINAL_STYLE "unknown"
